# Source: signalfx-agent/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: signalfx-agent-env
  labels:
    app: signalfx-agent-env
data:
# >>>> Set your environment variables here:
  CLUSTER_NAME: "<Update to your cluster name>"
  ENV_NAME: "<Update to one of eservice-prod, eservice-nonprod, liecomm-prod, liecomm-nonprod, accounts-prod, accounts-nonprod, necpc-prod,necpc-nonprod>"
  REALM: "us1"
  TRACE_ENDPOINT: "https://ingest.us1.signalfx.com/v2/trace"