apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pet-clinic
spec:
  selector:
    matchLabels:
      app: pet-clinic
  replicas: 1
  template: 
    metadata:
      labels:
        app: pet-clinic
    spec:
      containers:
      - name: pet-clinic
        image: katehymers/pet-clinic:latest
        env:
        - name: SIGNALFX_SERVICE_NAME
          value: "pet-clinic"
        - name: "SIGNALFX_AGENT_HOST"
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: SIGNALFX_SPAN_TAGS
          value: "release:k8s,version:1.0,clinic-name:PetsParadise"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pet-clinic-service
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pet-clinic
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-agent-readall-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-read-all
---